services: 
# WIREGUARD - route traffic for .arr's and download clients
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PEERDNS=off  # Disable WireGuard's DNS override
      - ALLOWEDIPS=0.0.0.0/0
      #0.0.0.0/1,128.0.0.0/1,192.168.110.0/24
      - LOG_CONFS=true
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /docker/appdata/wireguard:/config
      - /lib/modules:/lib/modules
    entrypoint: /config/initdns.sh
    ports:
      - 51820:51820/udp
      - 6789:6789
      - 7878:7878
      - 8989:8989
      - 5055:5055
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
# RADARR - Movie manager
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/radarr:/config 
      - /mnt/volume1/data:/data
    #ports:
      #- 7878:7878 # routed via Wireguard
    restart: unless-stopped
#    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/volume1/data:/data
    #ports:
      #- 8989:8989 # routed via Wireguard
    restart: unless-stopped
# Prowlarr - Radarr & Sonarr manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MONO_TLS_PROVIDER=legacy
      - MONO_IPV6=0
    volumes:
      - /docker/appdata/prowlarr:/config
      - /mnt/volume1/data:/data
    #ports: 
      #- 9696:9696 # routed via Wireguard
    restart: unless-stopped
# qBittorrent - torrent download client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:wireguard
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /mnt/volume1/data:/data
    #ports:
      #- 8081:8081 # routed via Wireguard
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped
#  Plex - media content manager
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      - TRANSCODE_DIR=/transcode
      #- PLEX_CLAIM=YourClaimCodeGoesHere #optional
      #- ADVERTISE_IP=http://
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /transcode:/transcode
      - /docker/appdata/plex:/config
      - /mnt/volume1/data/media/movies:/data/media/movies
      - /mnt/volume1/data/media/shows:/data/media/shows
    ports:
      - 32400:32400

    restart: unless-stopped
